name: CI/CD for Pokemoninom

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Shallow clones should be disabled for a better relevancy
        lfs: true # Enable LFS support

    - name: Set up Xcode
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        brew install fastlane

    - name: Build and Test
      run: |
        bundle install
        bundle exec fastlane ios test